# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/sahidalafzal/Desktop/MyDataBase

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/sahidalafzal/Desktop/MyDataBase

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sahidalafzal/Desktop/MyDataBase/CMakeFiles /Users/sahidalafzal/Desktop/MyDataBase//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sahidalafzal/Desktop/MyDataBase/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named irisdb

# Build rule for target.
irisdb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 irisdb
.PHONY : irisdb

# fast build rule for target.
irisdb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/build
.PHONY : irisdb/fast

Buffer/BufferPoolManager.o: Buffer/BufferPoolManager.cpp.o
.PHONY : Buffer/BufferPoolManager.o

# target to build an object file
Buffer/BufferPoolManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/Buffer/BufferPoolManager.cpp.o
.PHONY : Buffer/BufferPoolManager.cpp.o

Buffer/BufferPoolManager.i: Buffer/BufferPoolManager.cpp.i
.PHONY : Buffer/BufferPoolManager.i

# target to preprocess a source file
Buffer/BufferPoolManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/Buffer/BufferPoolManager.cpp.i
.PHONY : Buffer/BufferPoolManager.cpp.i

Buffer/BufferPoolManager.s: Buffer/BufferPoolManager.cpp.s
.PHONY : Buffer/BufferPoolManager.s

# target to generate assembly for a file
Buffer/BufferPoolManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/Buffer/BufferPoolManager.cpp.s
.PHONY : Buffer/BufferPoolManager.cpp.s

Buffer/LRUReplacer.o: Buffer/LRUReplacer.cpp.o
.PHONY : Buffer/LRUReplacer.o

# target to build an object file
Buffer/LRUReplacer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/Buffer/LRUReplacer.cpp.o
.PHONY : Buffer/LRUReplacer.cpp.o

Buffer/LRUReplacer.i: Buffer/LRUReplacer.cpp.i
.PHONY : Buffer/LRUReplacer.i

# target to preprocess a source file
Buffer/LRUReplacer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/Buffer/LRUReplacer.cpp.i
.PHONY : Buffer/LRUReplacer.cpp.i

Buffer/LRUReplacer.s: Buffer/LRUReplacer.cpp.s
.PHONY : Buffer/LRUReplacer.s

# target to generate assembly for a file
Buffer/LRUReplacer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/Buffer/LRUReplacer.cpp.s
.PHONY : Buffer/LRUReplacer.cpp.s

Buffer/Node.o: Buffer/Node.cpp.o
.PHONY : Buffer/Node.o

# target to build an object file
Buffer/Node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/Buffer/Node.cpp.o
.PHONY : Buffer/Node.cpp.o

Buffer/Node.i: Buffer/Node.cpp.i
.PHONY : Buffer/Node.i

# target to preprocess a source file
Buffer/Node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/Buffer/Node.cpp.i
.PHONY : Buffer/Node.cpp.i

Buffer/Node.s: Buffer/Node.cpp.s
.PHONY : Buffer/Node.s

# target to generate assembly for a file
Buffer/Node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/Buffer/Node.cpp.s
.PHONY : Buffer/Node.cpp.s

Buffer/Page.o: Buffer/Page.cpp.o
.PHONY : Buffer/Page.o

# target to build an object file
Buffer/Page.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/Buffer/Page.cpp.o
.PHONY : Buffer/Page.cpp.o

Buffer/Page.i: Buffer/Page.cpp.i
.PHONY : Buffer/Page.i

# target to preprocess a source file
Buffer/Page.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/Buffer/Page.cpp.i
.PHONY : Buffer/Page.cpp.i

Buffer/Page.s: Buffer/Page.cpp.s
.PHONY : Buffer/Page.s

# target to generate assembly for a file
Buffer/Page.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/Buffer/Page.cpp.s
.PHONY : Buffer/Page.cpp.s

DataRepresentationLayer/src/column.o: DataRepresentationLayer/src/column.cpp.o
.PHONY : DataRepresentationLayer/src/column.o

# target to build an object file
DataRepresentationLayer/src/column.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/DataRepresentationLayer/src/column.cpp.o
.PHONY : DataRepresentationLayer/src/column.cpp.o

DataRepresentationLayer/src/column.i: DataRepresentationLayer/src/column.cpp.i
.PHONY : DataRepresentationLayer/src/column.i

# target to preprocess a source file
DataRepresentationLayer/src/column.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/DataRepresentationLayer/src/column.cpp.i
.PHONY : DataRepresentationLayer/src/column.cpp.i

DataRepresentationLayer/src/column.s: DataRepresentationLayer/src/column.cpp.s
.PHONY : DataRepresentationLayer/src/column.s

# target to generate assembly for a file
DataRepresentationLayer/src/column.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/DataRepresentationLayer/src/column.cpp.s
.PHONY : DataRepresentationLayer/src/column.cpp.s

DataRepresentationLayer/src/schema.o: DataRepresentationLayer/src/schema.cpp.o
.PHONY : DataRepresentationLayer/src/schema.o

# target to build an object file
DataRepresentationLayer/src/schema.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/DataRepresentationLayer/src/schema.cpp.o
.PHONY : DataRepresentationLayer/src/schema.cpp.o

DataRepresentationLayer/src/schema.i: DataRepresentationLayer/src/schema.cpp.i
.PHONY : DataRepresentationLayer/src/schema.i

# target to preprocess a source file
DataRepresentationLayer/src/schema.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/DataRepresentationLayer/src/schema.cpp.i
.PHONY : DataRepresentationLayer/src/schema.cpp.i

DataRepresentationLayer/src/schema.s: DataRepresentationLayer/src/schema.cpp.s
.PHONY : DataRepresentationLayer/src/schema.s

# target to generate assembly for a file
DataRepresentationLayer/src/schema.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/DataRepresentationLayer/src/schema.cpp.s
.PHONY : DataRepresentationLayer/src/schema.cpp.s

DataRepresentationLayer/src/tuple.o: DataRepresentationLayer/src/tuple.cpp.o
.PHONY : DataRepresentationLayer/src/tuple.o

# target to build an object file
DataRepresentationLayer/src/tuple.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/DataRepresentationLayer/src/tuple.cpp.o
.PHONY : DataRepresentationLayer/src/tuple.cpp.o

DataRepresentationLayer/src/tuple.i: DataRepresentationLayer/src/tuple.cpp.i
.PHONY : DataRepresentationLayer/src/tuple.i

# target to preprocess a source file
DataRepresentationLayer/src/tuple.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/DataRepresentationLayer/src/tuple.cpp.i
.PHONY : DataRepresentationLayer/src/tuple.cpp.i

DataRepresentationLayer/src/tuple.s: DataRepresentationLayer/src/tuple.cpp.s
.PHONY : DataRepresentationLayer/src/tuple.s

# target to generate assembly for a file
DataRepresentationLayer/src/tuple.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/DataRepresentationLayer/src/tuple.cpp.s
.PHONY : DataRepresentationLayer/src/tuple.cpp.s

DataRepresentationLayer/src/value.o: DataRepresentationLayer/src/value.cpp.o
.PHONY : DataRepresentationLayer/src/value.o

# target to build an object file
DataRepresentationLayer/src/value.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/DataRepresentationLayer/src/value.cpp.o
.PHONY : DataRepresentationLayer/src/value.cpp.o

DataRepresentationLayer/src/value.i: DataRepresentationLayer/src/value.cpp.i
.PHONY : DataRepresentationLayer/src/value.i

# target to preprocess a source file
DataRepresentationLayer/src/value.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/DataRepresentationLayer/src/value.cpp.i
.PHONY : DataRepresentationLayer/src/value.cpp.i

DataRepresentationLayer/src/value.s: DataRepresentationLayer/src/value.cpp.s
.PHONY : DataRepresentationLayer/src/value.s

# target to generate assembly for a file
DataRepresentationLayer/src/value.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/DataRepresentationLayer/src/value.cpp.s
.PHONY : DataRepresentationLayer/src/value.cpp.s

Page/slotted_page.o: Page/slotted_page.cpp.o
.PHONY : Page/slotted_page.o

# target to build an object file
Page/slotted_page.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/Page/slotted_page.cpp.o
.PHONY : Page/slotted_page.cpp.o

Page/slotted_page.i: Page/slotted_page.cpp.i
.PHONY : Page/slotted_page.i

# target to preprocess a source file
Page/slotted_page.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/Page/slotted_page.cpp.i
.PHONY : Page/slotted_page.cpp.i

Page/slotted_page.s: Page/slotted_page.cpp.s
.PHONY : Page/slotted_page.s

# target to generate assembly for a file
Page/slotted_page.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/Page/slotted_page.cpp.s
.PHONY : Page/slotted_page.cpp.s

disk_manager.o: disk_manager.cpp.o
.PHONY : disk_manager.o

# target to build an object file
disk_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/disk_manager.cpp.o
.PHONY : disk_manager.cpp.o

disk_manager.i: disk_manager.cpp.i
.PHONY : disk_manager.i

# target to preprocess a source file
disk_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/disk_manager.cpp.i
.PHONY : disk_manager.cpp.i

disk_manager.s: disk_manager.cpp.s
.PHONY : disk_manager.s

# target to generate assembly for a file
disk_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/disk_manager.cpp.s
.PHONY : disk_manager.cpp.s

indexing/b_plus_internal_page.o: indexing/b_plus_internal_page.cpp.o
.PHONY : indexing/b_plus_internal_page.o

# target to build an object file
indexing/b_plus_internal_page.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/indexing/b_plus_internal_page.cpp.o
.PHONY : indexing/b_plus_internal_page.cpp.o

indexing/b_plus_internal_page.i: indexing/b_plus_internal_page.cpp.i
.PHONY : indexing/b_plus_internal_page.i

# target to preprocess a source file
indexing/b_plus_internal_page.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/indexing/b_plus_internal_page.cpp.i
.PHONY : indexing/b_plus_internal_page.cpp.i

indexing/b_plus_internal_page.s: indexing/b_plus_internal_page.cpp.s
.PHONY : indexing/b_plus_internal_page.s

# target to generate assembly for a file
indexing/b_plus_internal_page.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/indexing/b_plus_internal_page.cpp.s
.PHONY : indexing/b_plus_internal_page.cpp.s

indexing/b_plus_leaf_page.o: indexing/b_plus_leaf_page.cpp.o
.PHONY : indexing/b_plus_leaf_page.o

# target to build an object file
indexing/b_plus_leaf_page.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/indexing/b_plus_leaf_page.cpp.o
.PHONY : indexing/b_plus_leaf_page.cpp.o

indexing/b_plus_leaf_page.i: indexing/b_plus_leaf_page.cpp.i
.PHONY : indexing/b_plus_leaf_page.i

# target to preprocess a source file
indexing/b_plus_leaf_page.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/indexing/b_plus_leaf_page.cpp.i
.PHONY : indexing/b_plus_leaf_page.cpp.i

indexing/b_plus_leaf_page.s: indexing/b_plus_leaf_page.cpp.s
.PHONY : indexing/b_plus_leaf_page.s

# target to generate assembly for a file
indexing/b_plus_leaf_page.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/indexing/b_plus_leaf_page.cpp.s
.PHONY : indexing/b_plus_leaf_page.cpp.s

indexing/b_plus_tree.o: indexing/b_plus_tree.cpp.o
.PHONY : indexing/b_plus_tree.o

# target to build an object file
indexing/b_plus_tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/indexing/b_plus_tree.cpp.o
.PHONY : indexing/b_plus_tree.cpp.o

indexing/b_plus_tree.i: indexing/b_plus_tree.cpp.i
.PHONY : indexing/b_plus_tree.i

# target to preprocess a source file
indexing/b_plus_tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/indexing/b_plus_tree.cpp.i
.PHONY : indexing/b_plus_tree.cpp.i

indexing/b_plus_tree.s: indexing/b_plus_tree.cpp.s
.PHONY : indexing/b_plus_tree.s

# target to generate assembly for a file
indexing/b_plus_tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/indexing/b_plus_tree.cpp.s
.PHONY : indexing/b_plus_tree.cpp.s

indexing/b_plus_tree_page.o: indexing/b_plus_tree_page.cpp.o
.PHONY : indexing/b_plus_tree_page.o

# target to build an object file
indexing/b_plus_tree_page.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/indexing/b_plus_tree_page.cpp.o
.PHONY : indexing/b_plus_tree_page.cpp.o

indexing/b_plus_tree_page.i: indexing/b_plus_tree_page.cpp.i
.PHONY : indexing/b_plus_tree_page.i

# target to preprocess a source file
indexing/b_plus_tree_page.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/indexing/b_plus_tree_page.cpp.i
.PHONY : indexing/b_plus_tree_page.cpp.i

indexing/b_plus_tree_page.s: indexing/b_plus_tree_page.cpp.s
.PHONY : indexing/b_plus_tree_page.s

# target to generate assembly for a file
indexing/b_plus_tree_page.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/indexing/b_plus_tree_page.cpp.s
.PHONY : indexing/b_plus_tree_page.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irisdb.dir/build.make CMakeFiles/irisdb.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... irisdb"
	@echo "... Buffer/BufferPoolManager.o"
	@echo "... Buffer/BufferPoolManager.i"
	@echo "... Buffer/BufferPoolManager.s"
	@echo "... Buffer/LRUReplacer.o"
	@echo "... Buffer/LRUReplacer.i"
	@echo "... Buffer/LRUReplacer.s"
	@echo "... Buffer/Node.o"
	@echo "... Buffer/Node.i"
	@echo "... Buffer/Node.s"
	@echo "... Buffer/Page.o"
	@echo "... Buffer/Page.i"
	@echo "... Buffer/Page.s"
	@echo "... DataRepresentationLayer/src/column.o"
	@echo "... DataRepresentationLayer/src/column.i"
	@echo "... DataRepresentationLayer/src/column.s"
	@echo "... DataRepresentationLayer/src/schema.o"
	@echo "... DataRepresentationLayer/src/schema.i"
	@echo "... DataRepresentationLayer/src/schema.s"
	@echo "... DataRepresentationLayer/src/tuple.o"
	@echo "... DataRepresentationLayer/src/tuple.i"
	@echo "... DataRepresentationLayer/src/tuple.s"
	@echo "... DataRepresentationLayer/src/value.o"
	@echo "... DataRepresentationLayer/src/value.i"
	@echo "... DataRepresentationLayer/src/value.s"
	@echo "... Page/slotted_page.o"
	@echo "... Page/slotted_page.i"
	@echo "... Page/slotted_page.s"
	@echo "... disk_manager.o"
	@echo "... disk_manager.i"
	@echo "... disk_manager.s"
	@echo "... indexing/b_plus_internal_page.o"
	@echo "... indexing/b_plus_internal_page.i"
	@echo "... indexing/b_plus_internal_page.s"
	@echo "... indexing/b_plus_leaf_page.o"
	@echo "... indexing/b_plus_leaf_page.i"
	@echo "... indexing/b_plus_leaf_page.s"
	@echo "... indexing/b_plus_tree.o"
	@echo "... indexing/b_plus_tree.i"
	@echo "... indexing/b_plus_tree.s"
	@echo "... indexing/b_plus_tree_page.o"
	@echo "... indexing/b_plus_tree_page.i"
	@echo "... indexing/b_plus_tree_page.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

